// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shoootz.Store;

#nullable disable

namespace Shoootz.Store.Adapter.SQLite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260604150029_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Shoootz.Store.Entities.ShooterEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("Birthyear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Club")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Firstname")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Lastname")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Startnumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Team")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Shooters");
                });

            modelBuilder.Entity("Shoootz.Store.Entities.ShotEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DecValue")
                        .HasColumnType("REAL");

                    b.Property<string>("DiscType")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<double>("Distance")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsHot")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsValid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShooterId")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ShotDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShotInfoMenuId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShooterId");

                    b.HasIndex("ShotInfoMenuId");

                    b.ToTable("Shots");
                });

            modelBuilder.Entity("Shoootz.Store.Entities.ShotInfoEntity", b =>
                {
                    b.Property<string>("MenuId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MenuItemName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MenuPointName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("MenuId");

                    b.ToTable("ShotInfos");
                });

            modelBuilder.Entity("Shoootz.Store.Entities.ShotEntity", b =>
                {
                    b.HasOne("Shoootz.Store.Entities.ShooterEntity", "Shooter")
                        .WithMany("Shots")
                        .HasForeignKey("ShooterId");

                    b.HasOne("Shoootz.Store.Entities.ShotInfoEntity", "ShotInfo")
                        .WithMany("Shots")
                        .HasForeignKey("ShotInfoMenuId");

                    b.Navigation("Shooter");

                    b.Navigation("ShotInfo");
                });

            modelBuilder.Entity("Shoootz.Store.Entities.ShooterEntity", b =>
                {
                    b.Navigation("Shots");
                });

            modelBuilder.Entity("Shoootz.Store.Entities.ShotInfoEntity", b =>
                {
                    b.Navigation("Shots");
                });
#pragma warning restore 612, 618
        }
    }
}
