// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Shoootz.Store;

#nullable disable

namespace Shoootz.Store.Adapter.PostgreSQL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shoootz.Store.Entities.ShooterEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("Birthyear")
                        .HasColumnType("integer");

                    b.Property<string>("Club")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Firstname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Lastname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Startnumber")
                        .HasColumnType("integer");

                    b.Property<string>("Team")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Shooters");
                });

            modelBuilder.Entity("Shoootz.Store.Entities.ShotEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<double>("DecValue")
                        .HasColumnType("double precision");

                    b.Property<string>("DiscType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<double>("Distance")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsHot")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<string>("ShooterId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("ShotDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShotInfoMenuId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ShooterId");

                    b.HasIndex("ShotInfoMenuId");

                    b.ToTable("Shots");
                });

            modelBuilder.Entity("Shoootz.Store.Entities.ShotInfoEntity", b =>
                {
                    b.Property<string>("MenuId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MenuItemName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MenuPointName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("MenuId");

                    b.ToTable("ShotInfos");
                });

            modelBuilder.Entity("Shoootz.Store.Entities.ShotEntity", b =>
                {
                    b.HasOne("Shoootz.Store.Entities.ShooterEntity", "Shooter")
                        .WithMany("Shots")
                        .HasForeignKey("ShooterId");

                    b.HasOne("Shoootz.Store.Entities.ShotInfoEntity", "ShotInfo")
                        .WithMany("Shots")
                        .HasForeignKey("ShotInfoMenuId");

                    b.Navigation("Shooter");

                    b.Navigation("ShotInfo");
                });

            modelBuilder.Entity("Shoootz.Store.Entities.ShooterEntity", b =>
                {
                    b.Navigation("Shots");
                });

            modelBuilder.Entity("Shoootz.Store.Entities.ShotInfoEntity", b =>
                {
                    b.Navigation("Shots");
                });
#pragma warning restore 612, 618
        }
    }
}
